### ISSUE TITLE
Create Drive Train Config Firmware Component

### ISSUE THREAD

**Issue by robberwick** [thingswebuilt/osod24_firmware#1]
#### Issue Description
The Drive Train Config component is responsible for configuring the drivetrain. It provides values capturing the physical attributes of the robot required by various algorithms in the firmware, such as the wheelbase and wheel diameter. It can also provide optional parameters such as the maximum velocity, maximum acceleration, and maximum angular velocity.

#### Tasks
- [x] Implement the Drive Train Config firmware component.
- [x] Ensure the component captures essential physical attributes of the robot.
- [x] Incorporate optional parameters for maximum velocity, acceleration, and angular velocity.

#### Additional Information
More detailed information about the Drive Train Config component can be found in the architecture document.

**Comment by markmellors** [comment]
is this now entirely covered by 'drivetrain_config'?

**Comment by robberwick** [comment]
Let's say yes, and we can raise any specific issues if and when they arise.
