### ISSUE TITLE
Create Navigator Firmware Component

### ISSUE THREAD

**Issue by robberwick** [thingswebuilt/osod24_firmware#2]
#### Issue Description
The Navigator component is responsible for determining the robot's desired state. It takes in a state request and outputs a desired state. Additionally, it is responsible for converting high-level path planning requests from the Pi into a series of state requests for the State Manager. The Navigator also contains a control mux for switching control modes between the Pi and an RC transmitter.

#### Tasks
- [ ] Implement the Navigator firmware component.
- [ ] Develop logic to determine and output the desired state based on input state requests.
- [ ] Implement the control mux for switching between Pi and RC transmitter control.

#### Additional Information
More detailed information about the Navigator component can be found in the architecture document.

**Comment by markmellors** [comment]
what's left to do on this issue? `control mux for switching between Pi and RC transmitter control.` ?
we also need a "navigate to waypoint strategy", but I guess that might need to come after we've got the pi comms working

**Comment by markmellors** [comment]
from the docs: ` It [the Navigator] takes the current robot state as input,`  I think the Navigator doesn't currently get the state from `state_estimator`, so I guess that also needs doing, once 'wild_stab_at_a_state` is in `main`

**Comment by robberwick** [comment]
Well, I'm all for closing this vague, open ended issue in favour of further smaller more focused ones.

And I promise to raise less "boil the ocean" type issues in future 😉

**Comment by markmellors** [comment]
I think this has been acheived in PR #54 so this issue can be closed ? Techncially there isn't pi control yet, but the mux is in place for it
