### ISSUE TITLE
Create State Estimator Firmware Component

### ISSUE THREAD

**Issue by robberwick** [thingswebuilt/osod24_firmware#3]
#### Issue Description
The State Estimator component is responsible for estimating the state of the robot by gathering raw sensor data (e.g., IMU and encoders). It outputs both sensor state (raw state) and robot state (filtered state). These values are crucial for the functioning of the Navigator and the State Manager.

#### Tasks
- [ ] Implement the State Estimator firmware component.
- [ ] Incorporate logic to gather raw sensor data and output sensor state and filtered robot state.
- [ ] Ensure integration with the Navigator and State Manager.

#### Additional Information
More detailed information about the State Estimator component can be found in the architecture document.

**Comment by markmellors** [comment]
I think PR #54  addressed the remaing work on point 3, so this can be closed now?
